services:
  postgres:
    image: postgres
    container_name: huention-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: huention
    networks:
<<<<<<< HEAD:apps/backend/docker-compose.yml
      - app-network
=======
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data
>>>>>>> 5683ac5 (✅ add auto connect db in pg admin):apps/backend/docker-compose.dev.yml

  pgadmin:
    image: dpage/pgadmin4
    container_name: huention-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    networks:
      - app-network
    ports:
      - '5050:80'
<<<<<<< HEAD:apps/backend/docker-compose.yml

networks:
  app-network:
=======
    networks:
      - default
    volumes:
      - ./pgadmin-config/servers.json:/pgadmin4/servers.json
      - ./pgadmin-config/pgpass:/pgpass
    command: ['bash', '-c', 'chmod 600 /pgpass && /entrypoint.sh']

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
>>>>>>> 5683ac5 (✅ add auto connect db in pg admin):apps/backend/docker-compose.dev.yml
